apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata: 
  name: hpa-falgi-deployment
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: falgi-deployment
  minReplicas: 1 
  maxReplicas: 3
  metrics: 
    - type: Resource 
      resource: 
        name: cpu 
        target: 
          type: Utilization
          averageUtilization: 10
